CREATE TABLE PESSOA(
  ID INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(30) NOT NULL,
  NASCIMENTO DATE
)

INSERT INTO PESSOA (NOME, NASCIMENTO) VALUES ('NATHALY', '1990-05-14')
INSERT INTO PESSOA (NOME, NASCIMENTO) VALUES ('WILTON', '1995-03-12')
INSERT INTO PESSOA (NOME, NASCIMENTO) VALUES ('FRANCINE', '2001-12-07')